#!/bin/bash

die() {
    echo $1
    exit 1
}

IMAGE_DIR=build/${1:-initramfs-linux}

[[ -n $IMAGE_DIR ]] || die "Usage $0: INITRAMFS-DIR [IMAGE-FILE]"
[[ -d $IMAGE_DIR ]] || die "Unable to open directory $IMAGE_DIR."

img=${2:-$(basename $IMAGE_DIR).img}

if [[ -e build/$img ]] ; then
    echo -n "Do you want to override the exiting image $img? (Y/n) "
    read ans
    if [[ -n $ans ]] && [[ ! x$ans = "xy" ]] && [[ ! x$ans = "xY" ]] ; then
        exit 0;
    fi
fi

cd $IMAGE_DIR
find . -print0 | cpio -ov --null --format=newc > ../${img}.cpio
cd ..

cat ${img}.cpio | gzip -c > ${img}.gz && echo "build/${img}.gz is ready."
cat ${img}.cpio | xz -Ccrc32 -c   > ${img}.xz && echo "build/${img}.xz is ready."
cat ${img}.cpio | lz4 -lc > ${img}.lz4 && echo "build/${img}.lz4 is ready."

#for comp in gz xz lz4 ; do
#    mkimage -A arm -T ramdisk -C none -n uInitrd -d ${img}.${comp} ${workdir}/u$(basename ${img}).${comp}
#done

